function Hd = BPF_FIR
%BPF_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 14-Oct-2022 13:00:21

% Generalized REMEZ FIR Bandpass filter designed using the FIRGR function.

% All frequency values are in kHz.
Fs = 125;  % Sampling Frequency

Fstop1 = 39;     % First Stopband Frequency
Fpass1 = 39.5;   % First Passband Frequency
Fpass2 = 40.5;   % Second Passband Frequency
Fstop2 = 41;     % Second Stopband Frequency
Dstop1 = 0.001;  % First Stopband Attenuation
Dpass  = 0.1;    % Passband Ripple
Dstop2 = 0.001;  % Second Stopband Attenuation
dens   = 20;     % Density Factor

% Calculate the coefficients using the FIRGR function.
b  = firgr('minorder', [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 ...
           0 1 1 0 0], [Dstop1 Dpass Dstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
